# Nome da Actions:
name: Snake Game

on:
  schedule: 
    - cron: "* */12 * * *"

  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "fernandes.christ14@gmail.com"
          git fetch
          git checkout master

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: chrisFernandesDev
          # gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check Changes
        run: |
          git status
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git commit -am "Atualizar cobra de contribuições"
          fi

      - name: Push Changes
        run: git push origin master

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
