name: Snake Game

on:
  schedule: 
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "fernandes.christ14@gmail.com"
          git fetch
          git checkout main

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: chrisFernandesDev
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check Changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            git add -A
            git commit -m "Atualizar cobra de contribuições"
          else
            echo "No changes to commit."
          fi

      - name: Push Changes
        run: git push origin main

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
