# Nome da Actions:
name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"

  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: chrisFernandesDev
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check Changes
        run: git status

      - name: Commit and Push Changes
        run: |
          git config user.name "Nome do Usuário"
          git config user.email "email@example.com"
          git add dist/
          git commit -m "Atualizar cobra de contribuições"
          git push origin main

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
